// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('createOrgType', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('createOrgType', async function() {
    // Navigate to login page
    await driver.get("https://admin.stage.vcc.hebronsoft.com/auth/login")
    await driver.manage().window().setRect({ width: 1400, height: 900 })
    
    // Wait for and fill login form
    await driver.wait(until.elementLocated(By.id("login-email")), 10000, "Login email field not found")
    await driver.findElement(By.id("login-email")).sendKeys("qwe@qwe.com")
    await driver.findElement(By.id("login-pass")).sendKeys("qweQWE123")
    await driver.findElement(By.id("log-btn")).click()
    
    // Wait for navigation and click on My Organization
    await driver.wait(until.elementLocated(By.id("organization-btn")), 10000, "My Organization button not found")
    const myOrgButton = await driver.findElement(By.id("organization-btn"))
    await myOrgButton.click()
    
    // Wait for and click on Organization Types in the dropdown
    const orgTypesOption = await driver.wait(
      until.elementLocated(By.xpath("//div[contains(@class, 'item-title') and text()='Org Type']")),
      10000,
      "Org Type option not found"
    )
    await orgTypesOption.click()
    
    // Wait for and click Create Org Type button
    const createOrgTypeButton = await driver.wait(
      until.elementLocated(By.xpath("//button[contains(.,'Create Organization Type')]")),
      10000,
      "Create Organization Type button not found"
    )
    await createOrgTypeButton.click()
    
    // Wait for dialog to be fully loaded and visible
    const dialog = await driver.wait(
      until.elementLocated(By.css("mat-dialog-container#manage-community-partner-kind-of-dialog")),
      10000,
      "Org type dialog not found"
    )
    
    // Wait for dialog to be visible
    await driver.wait(until.elementIsVisible(dialog), 10000, "Dialog not visible")
    
    // Find and fill the Kind of Organization Type input
    const orgTypeInput = await driver.wait(
      until.elementLocated(By.css("mat-dialog-container#manage-community-partner-kind-of-dialog input[formcontrolname='name']")),
      10000,
      "Org type input not found"
    )
    await orgTypeInput.sendKeys("Test")
    
    // Submit form
    const submitButton = await driver.wait(
      until.elementLocated(By.css("mat-dialog-container#manage-community-partner-kind-of-dialog button[type='submit']")),
      10000,
      "Submit button not found"
    )
    await submitButton.click()
    
    // Wait for success toast
    await driver.wait(
      until.elementLocated(By.css("#toast-container div")),
      10000,
      "Success toast not found"
    )
    
    // Wait for table to be present
    await driver.wait(
      until.elementLocated(By.css("p-table")),
      10000,
      "Table not found"
    )
    
    // Wait for the new Org Type to appear in the table
    const orgTypeCell = await driver.wait(
      until.elementLocated(By.xpath("//div[contains(@class, 'body-1') and text()=' Test ']")),
      10000,
      "New Org Type not found in table"
    )
    
    // Assert that the row exists
    assert.ok(orgTypeCell, "Row with new Org Type should exist")
  })
})