// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('createGoods', function () {
    this.timeout(30000)
    let driver
    let vars
    beforeEach(async function () {
        driver = await new Builder().forBrowser('chrome').build()
        vars = {}
    })
    afterEach(async function () {
        await driver.quit();
    })
    it('createGoods', async function () {
        // 1. Navigate to login page
        await driver.get("https://admin.stage.vcc.hebronsoft.com/auth/login")
        await driver.manage().window().setRect({ width: 1440, height: 900 })

        // 2. Wait for and fill login form
        await driver.wait(until.elementLocated(By.id("login-email")), 10000, "Login email field not found")
        await driver.findElement(By.id("login-email")).sendKeys("qwe@qwe.com")
        await driver.findElement(By.id("login-pass")).sendKeys("qweQWE123")
        await driver.findElement(By.id("log-btn")).click()

        // 3. Wait for navigation and click on Partners
        await driver.wait(until.elementLocated(By.id("partners-btn")), 10000, "Partners button not found")
        const partnersButton = await driver.findElement(By.id("partners-btn"))
        await partnersButton.click()

        // 4. Click Community Partners
        const communityPartnersOption = await driver.wait(
            until.elementLocated(By.xpath("//div[contains(@class, 'item-title') and text()='Community Partners']")),
            10000
        )
        await communityPartnersOption.click()

        // 5. Wait for filter input and filter for 'hebron'
        await driver.wait(until.urlContains('/company/list'), 10000)
        const nameFilterInput = await driver.wait(
            until.elementLocated(By.css('input.p-column-filter.max-with.p-inputtext.p-component')),
            10000
        )
        await nameFilterInput.clear()
        await nameFilterInput.sendKeys('hebron')

        // 6. Wait for HEBRON row and click it
        const hebronRow = await driver.wait(
            until.elementLocated(By.xpath("//div[contains(@class, 'pointable') and contains(translate(normalize-space(text()), 'abcdefghijklmnopqrstuvwxyz', 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'), 'HEBRON')]")),
            10000
        )
        await driver.wait(until.elementIsVisible(hebronRow), 10000)
        await hebronRow.click()

        // 7. Click the "4. Request Goods" tab
        const requestGoodsTab = await driver.wait(
            until.elementLocated(By.xpath("//a[contains(@class, 'body-2') and contains(normalize-space(text()), '4. Request Goods')]")),
            10000
        )
        await driver.wait(until.elementIsVisible(requestGoodsTab), 10000)
        await requestGoodsTab.click()

        // 8. Wait for and click Create Needs For Goods button
        const createNeedsForGoodsButton = await driver.wait(
            until.elementLocated(By.xpath("//button[contains(.,'Create Needs For Goods')]")),
            10000
        )
        await createNeedsForGoodsButton.click()

        // 9. Handle new tab that opens
        await driver.wait(async () => {
            const handles = await driver.getAllWindowHandles();
            return handles.length > 1;
        }, 10000, "New tab did not open");

        const handles = await driver.getAllWindowHandles();
        await driver.switchTo().window(handles[handles.length - 1]);

        // 10. Wait for the new page to load with the expected URL
        await driver.wait(until.urlContains('/need/create'), 10000, "New tab did not load the expected URL");
        await driver.wait(until.urlContains('partnersId='), 10000, "URL does not contain partnersId parameter");

        // 11.Wait for page to fully load
        await driver.sleep(2000);

        // Fill in Title using formcontrolname attributes
        const titleInput = await driver.wait(
            until.elementLocated(By.css(" input[formcontrolname='title']")),
            10000,
            "Title input not found"
        )
        await titleInput.sendKeys("Hygiene Kits for the Homeless")

        // 13. Fill in Mini Description
        const miniDescriptionInput = await driver.findElement(By.css('.mini-description-input'));
        await miniDescriptionInput.click();
        const miniDescText = 'Donate personal hygiene items to support individuals experiencing homelessness.';
        for (const char of miniDescText) {
            await miniDescriptionInput.sendKeys(char);
        }
        await driver.executeScript("arguments[0].blur();", miniDescriptionInput);
        // 14. Focus the Title input to help trigger validation
        const titleInputFocus = await driver.findElement(By.css("input[formcontrolname='title']"));
        await titleInputFocus.click();

        // 15. Fill in Description using sendKeys and blur
        const descriptionInput = await driver.findElement(By.xpath("//ngx-editor/div/div"));
        await descriptionInput.click();
        await descriptionInput.sendKeys('Our organization is assembling hygiene kits for distribution to people living on the streets and in shelters. We are seeking donations of travel-size shampoo, soap, toothpaste, toothbrushes, deodorant, feminine hygiene products, and socks. These simple items help restore dignity and improve daily living conditions for those in need. All donations will be sorted and packed by volunteers before being distributed throughout the city.');
        await driver.executeScript("arguments[0].blur();", descriptionInput);

        // 16. Select 'Ongoing' from the Type dropdown using JavaScript click
        const typeDropdown = await driver.findElement(By.css('mat-select[formcontrolname="type"]'));
        await typeDropdown.click();
        await driver.wait(until.elementLocated(By.css('.mat-select-panel')), 5000);
        const ongoingOption = await driver.findElement(By.xpath("//mat-option//span[contains(text(), 'Ongoing')]"));
        await driver.executeScript("arguments[0].click();", ongoingOption);
        await driver.sleep(500);

        // 17.Click the dropdown and wait for options panel
        await driver.findElement(By.id("mat-select-value-1")).click()

        // 18. Wait for the dropdown panel to be visible
        await driver.wait(
            until.elementLocated(By.css("#mat-option-0 > .mat-option-text")),
            10000,
            "Dropdown panel not found"
        )

        // 19. Wait for save button to be present
        await driver.wait(until.elementLocated(By.id("save-section-btn")), 10000);
        const saveButton = await driver.findElement(By.id("save-section-btn"));
        const isDisplayed = await saveButton.isDisplayed();
        const isEnabled = await saveButton.isEnabled();
        const isDisabledAttr = await saveButton.getAttribute('disabled');
        console.log("Save button displayed:", isDisplayed, "enabled:", isEnabled, "disabled attribute:", isDisabledAttr);
        await driver.wait(until.elementIsEnabled(saveButton), 10000);

        // 20 Click save button using JavaScript executor
        await driver.executeScript("arguments[0].click();", saveButton)

        // 21. Wait for and verify toast message
        await driver.wait(until.elementLocated(By.css(".toast-message")), 10000)
        const toastMessage = await driver.findElement(By.css(".toast-message"))
        await driver.wait(until.elementIsVisible(toastMessage), 10000)

        // 22. Wait for table to be present
        await driver.wait(
            until.elementLocated(By.css("p-table")),
            10000,
            "Table not found"
        )

        // 23.Wait for the new Goods to appear in the table
        const goodsCell = await driver.wait(
            until.elementLocated(By.xpath("//div[contains(@class, 'body-1') and text()=' Hygiene Kits for the Homeless ']")),
            10000,
            "New Goods not found in table"
        )

        // 24. Assert that the row exists
        assert.ok(goodsCell, "Row with new Goods should exist")

        await driver.close()
    })
})